on:
  push:
    branches:
      - master

name: Genymotion Cloud SaaS

jobs:
  test:
    name: Start Genymotion Cloud SaaS instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Start Genymotion Cloud SaaS instance
        uses: genymobile/genymotion-saas-github-action@v0.4
        with:
          email: "callmeeyan21@gmail.com"
          password: "callmeeyan21"
          recipe_uuid: 	e104f058-b291-4764-8e0d-d9ff78a41192

      - name: Build with Maven
        run: mvn -B package --file pom.xml

#      - name: Run MOBILE test
#        run: mvn clean verify